// Package transactions defines the transaction data models.
package transactions

import (
	"time"
)

// Status represents the transaction status in SEP flow.
type Status string

const (
	StatusPending  Status = "PENDING"
	StatusPaid     Status = "PAID"
	StatusVerified Status = "VERIFIED"
	StatusReversed Status = "REVERSED"
	StatusFailed   Status = "FAILED"
)

// Transaction represents a payment transaction in the SEP system.
type Transaction struct {
	// RefNum is the transaction reference number (token) generated by the gateway
	RefNum string `json:"RefNum"`

	// ResNum is the merchant's reservation number
	ResNum string `json:"ResNum"`

	// TerminalId is the terminal ID
	TerminalId string `json:"TerminalId"`

	// Amount in Rials
	Amount int64 `json:"Amount"`

	// Status of the transaction
	Status Status `json:"Status"`

	// RedirectUrl where customer should be redirected after payment
	RedirectUrl string `json:"RedirectUrl,omitempty"`

	// MerchantId who owns this transaction
	MerchantId string `json:"MerchantId,omitempty"`

	// OrderId is the order identifier
	OrderId string `json:"OrderId,omitempty"`

	// CellNumber is the customer's cell phone number
	CellNumber string `json:"CellNumber,omitempty"`

	// Description is the transaction description
	Description string `json:"Description,omitempty"`

	// CreatedAt timestamp
	CreatedAt time.Time `json:"CreatedAt"`

	// UpdatedAt timestamp
	UpdatedAt time.Time `json:"UpdatedAt"`
}
